env:
  LC_ALL: "en_US.UTF-8"

window:
  dimensions:
    columns: 125
    lines: 35

  padding:
    x: 0
    y: 0

  dynamic_padding: false

  decorations: full

  startup_mode: Windowed

  title: Alacritty

scrolling:
  history: 5000

  multiplier: 3

font:
  normal:
    family: Mononoki Nerd Font
    style: Medium

  bold:
    family: Mononoki Nerd Font
    style: Bold

  italic:
    family: Mononoki Nerd Font
    style: Italic

  bold_italic:
    family: Mononoki Nerd Font
    style: Bold Italic

  size: 13.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

draw_bold_text_with_bright_colors: false

# Ocean dark colours
colors:
  primary:
    background: "0x2b303b"
    foreground: "0xc0c5ce"

  normal:
    black: "0x2b303b"
    red: "0xbf616a"
    green: "0xa3be8c"
    yellow: "0xebcb8b"
    blue: "0x8fa1b3"
    magenta: "0xb48ead"
    cyan: "0x96b5b4"
    white: "0xc0c5ce"

  bright:
    black: "0x65737e"
    red: "0xbf616a"
    green: "0xa3be8c"
    yellow: "0xebcb8b"
    blue: "0x8fa1b3"
    magenta: "0xb48ead"
    cyan: "0x96b5b4"
    white: "0xeff1f5"

# Pop!_OS colours
#colors:
#  primary:
#    background: "#333333"
#    foreground: "#F2F2F2"

#  normal:
#    black: "#333333"
#    red: "#CC0000"
#    green: "#4E9A06"
#    yellow: "#C4A000"
#    blue: "#3465A4"
#    magenta: "#75507B"
#    cyan: "#06989A"
#    white: "#D3D7CF"

#  bright:
#    black: "#88807C"
#    red: "#F15D22"
#    green: "#73C48F"
#    yellow: "#FFCE51"
#    blue: "#48B9C7"
#    magenta: "#AD7FA8"
#    cyan: "#34E2E2"
#    white: "#EEEEEC"

bell:
  animation: EaseOutExpo
  duration: 0
  color: "0xffffff"

background_opacity: 0.9

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'

  save_to_clipboard: true

window.dynamic_title: true

cursor:
  style: Block

  unfocused_hollow: true

live_config_reload: true

shell:
  program: /bin/zsh

working_directory: None

debug:
  render_timer: false

  persistent_logging: false

  log_level: OFF

  print_events: false

  ref_test: false

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  hide_when_typing: false

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

key_bindings:
  # (Windows/Linux only)
  - { key: Q, mods: Control, action: Quit }
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
  - { key: Return, mods: Alt, action: ToggleFullscreen }
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Insert, mods: Shift, action: PasteSelection }

  # (macOS only)
  - { key: Key0, mods: Command, action: ResetFontSize }
  - { key: Equals, mods: Command, action: IncreaseFontSize }
  - { key: Minus, mods: Command, action: DecreaseFontSize }
  - { key: K, mods: Command, action: ClearHistory }
  - { key: K, mods: Command, chars: "\x0c" }
  - { key: V, mods: Command, action: Paste }
  - { key: C, mods: Command, action: Copy }
  - { key: H, mods: Command, action: Hide }
  - { key: Q, mods: Command, action: Quit }
  - { key: W, mods: Command, action: Quit }
  - { key: F, mods: Command|Control, action: ToggleFullscreen }

  - { key: Paste, action: Paste }
  - { key: Copy, action: Copy }
  - { key: L, mods: Control, action: ClearLogNotice }
  - { key: L, mods: Control, chars: "\x0c" }
  - { key: PageUp, mods: Shift, action: ScrollPageUp, mode: ~Alt }
  - { key: PageDown, mods: Shift, action: ScrollPageDown, mode: ~Alt }
  - { key: Home, mods: Shift, action: ScrollToTop, mode: ~Alt }
  - { key: End, mods: Shift, action: ScrollToBottom, mode: ~Alt }
