env:
  LC_ALL: "en_US.UTF-8"

window:
  dimensions:
    columns: 125
    lines: 35

  padding:
    x: 0
    y: 0

  dynamic_padding: false

  decorations: full

  startup_mode: Windowed

  title: Alacritty

scrolling:
  history: 5000

  multiplier: 3

font:
  normal:
    family: Mononoki Nerd Font Mono
    style: Medium

  bold:
    family: Mononoki Nerd Font Mono
    style: Bold

  italic:
    family: Mononoki Nerd Font Mono
    style: Italic

  bold_italic:
    family: Mononoki Nerd Font Mono
    style: Bold Italic

  size: 13.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

draw_bold_text_with_bright_colors: false

# Material Ocean colours
colors:
  primary:
    background: "0x0f111a"
    foreground: "0xD8DEE9"
  cursor:
    cursor: "0xff4151"
  normal:
    black: "0x4C566A"
    red: "0xBF616A"
    green: "0xA3BE8C"
    yellow: "0xEBCB8B"
    blue: "0x81A1C1"
    magenta: "0xB48EAD"
    cyan: "0x88C0D0"
    white: "0xE5E9F0"

# # One Dark colours
# colors:
#   # Default colors
#   primary:
#     background: "0x1e2127"
#     foreground: "0xabb2bf"
#     bright_foreground: "0xe6efff"

#   # Normal colors
#   normal:
#     black: "0x1e2127"
#     red: "0xe06c75"
#     green: "0x98c379"
#     yellow: "0xd19a66"
#     blue: "0x61afef"
#     magenta: "0xc678dd"
#     cyan: "0x56b6c2"
#     white: "0x828791"

#   # Bright colors
#   bright:
#     black: "0x5c6370"
#     red: "0xe06c75"
#     green: "0x98c379"
#     yellow: "0xd19a66"
#     blue: "0x61afef"
#     magenta: "0xc678dd"
#     cyan: "0x56b6c2"
#     white: "0xe6efff"

#   # Dim colors
#   dim:
#     black: "0x1e2127"
#     red: "0xe06c75"
#     green: "0x98c379"
#     yellow: "0xd19a66"
#     blue: "0x61afef"
#     magenta: "0xc678dd"
#     cyan: "0x56b6c2"
#     white: "0x828791"

bell:
  animation: EaseOutExpo
  duration: 0
  color: "0xffffff"

background_opacity: 0.9

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'

  save_to_clipboard: true

window.dynamic_title: true

cursor:
  style: Block

  unfocused_hollow: true

live_config_reload: true

shell:
  program: /bin/zsh

working_directory: None

debug:
  render_timer: false

  persistent_logging: false

  log_level: OFF

  print_events: false

  ref_test: false

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  hide_when_typing: false

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

key_bindings:
  - { key: Q, mods: Control, action: Quit }
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
  - { key: Return, mods: Alt, action: ToggleFullscreen }
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Insert, mods: Shift, action: PasteSelection }
